<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\User::create([
        	'name' => 'Super',
            'lastname' => 'Admin',
            'phone' => '12345678',
        	'photo' => 'usuario.png',
        	'slug' => 'super-admin',
        	'email' => 'admin@gmail.com',
        	'password' => bcrypt('12345678'),
        	'state' => "1",
            'type' => 1
        ]);

        // factory(App\User::class, 100)->create();

        // factory(App\Implementer::class, 100)->create();

        // factory(App\Testimonial::class, 500)->create();

        $users = [
            ['id' => 2, 'name' => 'Mike', 'lastname' => 'Abercrombie', 'phone' => '12345678', 'photo' => 'mike-abercrombie.jpg', 'slug' => 'mike-abercrombie', 'email' => 'mike.abercrombie@gmail.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 3, 'name' => 'Michael', 'lastname' => 'Bloch', 'phone' => '12345678', 'photo' => 'michael-bloch.jpg', 'slug' => 'michael-bloch', 'email' => 'michael.bloch@gmail.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 4, 'name' => 'Ross', 'lastname' => 'Foca', 'phone' => '4438640569', 'photo' => 'ross-foca.jpg', 'slug' => 'ross-foca', 'email' => 'Ross@power6group.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 5, 'name' => 'Liza', 'lastname' => 'Gonzales', 'phone' => '12345678', 'photo' => 'liza-gonzales.jpg', 'slug' => 'liza-gonzales', 'email' => 'liza.gonzales@gmail.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 6, 'name' => 'Angela', 'lastname' => 'Kalemis', 'phone' => '7327627162', 'photo' => 'angela-kalemis.jpeg', 'slug' => 'angela-kalemis', 'email' => 'Angela@4teamgrowth.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 7, 'name' => 'Ron', 'lastname' => 'Levene', 'phone' => '12345678', 'photo' => 'ron-levene.jpg', 'slug' => 'ron-levene', 'email' => 'ron.levene@gmail.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 8, 'name' => 'Ben', 'lastname' => 'Snyder', 'phone' => '12345678', 'photo' => 'ben-snyder.jpg', 'slug' => 'ben-snyder', 'email' => 'ben.snyder@gmail.com', 'password' => NULL, 'state' => "1", 'type' => "2"],
            ['id' => 9, 'name' => 'Jessica', 'lastname' => 'Stackpoole', 'phone' => '6026165160', 'photo' => 'jessica-stackpoole.jpg', 'slug' => 'jessica-stackpoole', 'email' => 'jessica@movetheneedle.com', 'password' => NULL, 'state' => "1", 'type' => "2"]
        ];
        DB::table('users')->insert($users);

        $implementers = [
            ['id' => 1, 'title' => '1', 'ypo_chapter' => 'YPO Angeleno Gold', 'service_area' => 'Greater Los Angeles', 'address' => 'Los Angeles, CA 90045', 'lat' => '34.0207305', 'lng' => '-118.6919311', 'experience' => "<p>Mike joined the <a href='https://www.ypo.org'>Young President’s Organization (YPO)</a> in 2001.</p><p>In 2015, Mike sold his training business to a global IT training organization and exited the business to focus on helping business leaders implement EOS. As a Certified EOS Implementer, Mike combines his business experience and love of teaching and group facilitation to fulfill his dream of helping other entrepreneurs after he was finished with his own business.</p><p>Mike is a respected YPO resource for forums, a YPO Certified Forum Facilitator and has serviced on the YPO International Forum Committee and is the co-author of the YPO Gold Forum Jumpstart program.</p><p>His business background provides context for the power and application of the EOS® tools in an entrepreneurial company. Couple that with his 10 years of teaching and facilitating business executives, Mike is able to help his clients navigate the tough but powerful conversations needed to move their business forward. The result is an aligned vision, better execution, a healthier leadership team, and organizational results.</p><p>In 2017 Mike was invited on to the EOS Worldwide Coaching team where he helps mentor new EOS Implementers on their journey to mastery in helping leadership teams get what they want from their businesses.</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=091ad30f-77e3-de11-8d75-005056923298&name=Member%20Directory', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 2],
            ['id' => 2, 'title' => '2', 'ypo_chapter' => 'YPO Patriot Gold / YPO Gold New England', 'service_area' => 'New England and New York', 'address' => 'Boston and New York', 'lat' => '42.3145186', 'lng' => '-71.1103703', 'experience' => "<p>Michael Bloch (YPO Patriot Gold / YPO Gold New England) is a Professional EOS® Implementer and  sought after resource to YPO chapters, forums, regions and networks.  Michael has been both the 4th generation CEO of his family business and the founder of two successful start-ups, so he has a unique insider’s perspective on the pressures and challenges faced by CEOs and senior leaders in both family and entrepreneurial businesses.</p><p>Since successfully exiting his businesses, Michael has trained, facilitated and coached over 3,000 CEOs and business leaders around the world.</p><p>Combining his practical experience as a CEO and company founder with the authenticity, vulnerability and emotional intelligence he brings as a top-rated YPO Certified Forum Facilitator, Michael helps entrepreneurs, business owners and leadership teams create the vision, accountability and trust necessary to get everything they want from their business.</p><p>In addition to his work as a EOS® implementer and forum facilitator, Michael is an active YPO member having held leadership roles at the chapter, regional and international levels. Michael is the recipient of four prestigious YPO International Best of the Best Awards and recently received a Legacy Award for his long-term positive impact on the organization.  In 2019, Michael served as Chair of the YPO Global Leadership Conference held in Cape Town South Africa, receiving the highest scores ever for a non-U.S. based GLC.</p><p>Outside of work, Michael enjoys documentary filmmaking and is an avid cyclist. As a cancer survivor, he is also an active fundraiser for cancer research. Michael and his spouse Sondra have three young adult sons and reside just outside Boston.</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=a20d610e-76e3-de11-8d75-005056923298', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 3],
            ['id' => 3, 'title' => '2', 'ypo_chapter' => 'YPO Gold Washington DC - Baltimore', 'service_area' => 'MD, Eastern Shore, DE, Central PA, Philly, DC, Northern VA, & Richmond', 'address' => 'Annapolis, MD 21401', 'lat' => '38.9859644', 'lng' => '-76.6152376', 'experience' => "<p>Ross is the founder of Power 6 Group, growth focused and passionate about building leadership teams. Over the span of his 25-year career, prior to focusing 100% on EOS Implementations, he has been a member of the leadership teams of entrepreneurial companies from $5M to $5B in revenue. He started his career in accounting in finance, progressed to CFO, then took the leap to operations. His last 15 years were focused as an owner and President/CEO of several food manufacturing and distribution companies. He led one of these company’s revenue from $70M to $300M. After a successful exit, he shifted his focus to helping others. Currently he focuses his efforts on helping entrepreneurs and leadership teams get what they want out of their business and live a better life.</p><p>He enjoys family time with his wife of over 25 years & two college age children, traveling, helping his clients and competitive tennis. Ross was member of the Young Presidents’ Organization (YPO) for 10 years and is now is a member of the Baltimore / DC YPO Gold chapter. Ross often volunteers his time to sit on industries boards and mentoring others. He is currently an active mentor for the University of Maryland’s football program, helping players be successful off the field and after graduation. Ross has an MBA from Loyola University and BA from UMBC in Economics.</p><p>Ross would love to help you and your leadership team achieve your vision.</p><p>Contact: 443-864-0569 (mobile) Ross@power6group.com</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=1452144d-5a79-df11-b840-0050569257ef', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 4],
            ['id' => 4, 'title' => '2', 'ypo_chapter' => 'YPO Colorado', 'service_area' => 'Denver metropolitan area, Colorado Springs, Boulder, Milwaukee, Madison, and the Chicagoland area', 'address' => 'Englewood, CO 80113', 'lat' => '39.6477343', 'lng' => '-105.0322101', 'experience' => "<p>Teams that run on EOS “run a better business and live a better life!” In fact, Lisa experienced these very benefits in her family's YPO business.</p><p>Before becoming a Professional Implementer, Lisa was a business lawyer, specializing in employment defense law for companies from Fortune 500 to start-ups. In 2001, she was recruited from the corporate world and joined YPO and GOT member, Patrick Condon in his start-up: a design/build residential remodel company – Finished Basement Company. The company expanded to locations in Colorado, Minnesota, and Illinois. After years of using various tools to improve operations, she implemented EOS.</p><p>EOS made an impact across the business: consistent profits, documented processes, healthy margins, and a strong leadership team. The transformation was DRAMATIC!</p><p>Overall, EOS improved the company culture and transformed her life! She became committed to sharing EOS with other growth-minded companies and transitioned out of the organization to become formally trained as an EOS Implementer.</p><p>Lisa is a student of business and has been a board member of YPO Colorado, and a member of EO (YEO), and Vistage. She has been an EOS peer group chair and a talented facilitator, teacher, and coach who understands the practical realities of introducing EOS to your business.  From corporate experience to specialized training to support family businesses her breadth of experience is a benefit to her clients.</p><p>Lisa notes, 'Business leaders create all the great things that we experience in our world. Healthy leadership teams help make them a reality.' Lisa is passionate about supporting you and your leadership team and will help you take your business to the next level.</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=241b9dd8-2945-e111-96fc-0050569257ef', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 5],
            ['id' => 5, 'title' => '1', 'ypo_chapter' => 'YPO Philadelphia', 'service_area' => 'Greater Philadelphia Region, New Jersey, Delaware', 'address' => 'King of Prussia, PA 19406', 'lat' => '40.0948184', 'lng' => '-75.4165006', 'experience' => "<p>Angela grew up in a family business and life revolved around it. This upbringing exposed her to the struggles, difficulties and instability that many business owners face. And so, when Angela graduated college, rather than going into the family business, she went into corporate America and worked for several large corporations. Her longest tenure was 17+ years at Booz Allen, a global technology leader.</p><p>Angela is a Certified Forum Facilitator by YPO and has the privilege of working with entrepreneurs around the world, helping them develop and grow and become better leaders. Angela is married to a serial entrepreneur and originally began mastering the EOS system with the intention of implementing it in his company, but she immediately connected to the system and found her own entrepreneurial passion to help other business owners achieve outstanding results.</p><p>Angela combines her passion for teaching and facilitating with 20+ years of business experience. Angela knows the challenges of growing and running businesses and how to powerfully apply the EOS tools to create structure and accountability to excel in entrepreneurial environments.</p><p>CONTACT ANGELA TO SEE WHAT IMPLEMENTING THE ENTREPRENEURIAL OPERATING SYSTEM® COULD DO FOR YOUR BUSINESS: 732.762.7162 or at Angela@4teamgrowth.com.</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=44ce6f33-591d-e211-9a96-0050569257ef&mode=edit', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 6],
            ['id' => 6, 'title' => '2', 'ypo_chapter' => 'YPO Connecticut River Valley, YPO Philadelphia', 'service_area' => 'New England, New York, New Jersey and Eastern Pennsylvania', 'address' => 'Manchester, Vermont', 'lat' => '43.1610712', 'lng' => '-73.106882', 'experience' => "<p>Ron grew up in an entrepreneurial household, his family was in the auto parts business. He worked in and around the business from the age of 8. After a few years in finance in New York City he figured out he didn’t fit in that corporate world and fled!  Ron was asked to return to the family auto parts business in Upstate NY. He struggled in the chaos of trying to redirect a 70-year-old family business until he applied many of the EOS tools.</p><p>Ron and the new leadership team grew revenue 5X, and profitability 7X, and from 35 employees to over 170 employees.  Together they were able to cultivate vision, develop a positive culture with an accountable leadership team and create a thriving, growing business, while also finding balance, fun and joy in life. Ron eventually created a successful exit for his family, selling to a public company.</p><p>As Ron was catching his breath and trying to find some life balance, he quickly found himself asked to work with other owners. Ron found a passion in acting as an advisor to over a dozen companies and discovered a true joy and knack for helping these other frustrated entrepreneurs and start-up founders.</p><p>During this time Ron returned to school and earned a Masters in Applied Positive Psychology, at the University of Pennsylvania, and went deeper into his YPO experience becoming a Certified Forum Facilitator, (CFF).  He has been an Adjunct Prof of Entrepreneurship at Drexel University and has worked with the US Military teaching entrepreneurial process to soldiers and veterans transitioning to civilian life.</p><p>When someone handed Ron a copy of Traction he had the light-bulb moment and realized this was the HOW to the Why and What of Business. EOS is the assemblage of the great tools of business into an operating system that can be applied across industries.</p><p>Ron has developed a straightforward authentic approach to helping entrepreneurs and leadership teams get what they want from their business and life. If you feel like your business has hit a ceiling, your leadership team isn’t working effectively, or you are just not getting what you want out of your business then EOS and Ron might be for you.</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=a477a0e5-7be3-de11-8d75-005056923298', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 7],
            ['id' => 7, 'title' => '2', 'ypo_chapter' => 'YPO Gold Rocky Mountain', 'service_area' => 'United States', 'address' => 'Denver, Colorado 80015', 'lat' => '39.7645187', 'lng' => '-104.9951981', 'experience' => "<p>A perpetual entrepreneur, Ben Snyder has owned and operated four businesses over the past 20 years, overseeing all phases of business growth—and all the issues those entail. He brings that real-world expertise and the Entrepreneurial Operating System to help clients navigate the challenges of day-to-day operations and the demands of running and growing a successful business.</p><p>In his past businesses, Ben set a high standard for best-in-class practices. This includes developing strategies, execution plans and delivering on initiatives; reengineering operational processes and instituting efficiencies; expanding into global markets and aligning teams around a companywide customer-driven value chain. In addition to his depth of experience as an owner/operator, Ben has a long history as a management consultant and coach, working with executives in companies such as JP Morgan Chase, Nike, Anthem, McDonalds, Cigna and AstraZeneca.</p><p>A current member of the Young Presidents Organization, Ben played baseball professionally with the Houston Astros organization, speaks frequently and is the author of the book “Everything’s a Project”.</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=6eaa5afa-79e3-de11-8d75-005056923298', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 8],
            ['id' => 8, 'title' => '1', 'ypo_chapter' => 'YPO Arizona', 'service_area' => 'Arizona, California, Colorado, Utah, Oregon, and Nevada', 'address' => 'Phoenix, AZ 85253', 'lat' => '33.543668', 'lng' => '-112.0024752', 'experience' => "<p>Jessica is an entrepreneurial, gig economy expert, fast-moving CEO with more than 22 years of experience in pioneering and scaling world-class companies and building large teams in complex environments. Her superpower is leveraging her vast network to drive award-winning sales growth while increasing margins and operational performance. She has a dynamic skill set, to include: developing drama-free cultures, organizational development, non-traditional marketing, and turnaround experience. She has a proven track-record in professional implementation of the Entrepreneurial Operating System (EOS) to align leadership teams with their vision, expedite accountability and results, and simplify processes, for mostly YPO companies. Jessica limits the number of EOS Clients she takes on, in order to consistently deliver white-glove service to every single client.</p><p>For 18 years, Jessica was Founder & CEO of a leading agency in event/experiential marketing staffing and execution with 10,000 W2 field employees throughout the US and Canada. Their Fortune 500 clients included: Coca-Cola (VEB), Match.com, State Farm, Nintendo, Samsung, gogo inflight Internet, Singularity University, etc.</p><p>Jessica is also a Founding Partner of Fenix Verify and Fenix Management Advisors with 3 other YPO Partners.</p><p>Jessica received her BS Degree in Mass Communications (Advertising) from Towson University and is and a 2007 graduate of the MIT Entrepreneurial Master’s Program (EMP). She is an active member of Young Presidents Organization (YPO), since 2010, and a former member of EO.</p><p>Jessica has a blended family of four daughters. When she isn’t working, you can usually find her at Orange Theory or yoga, in nature, drinking wine and dining, or on an adventure somewhere around the world.</p><p>Let's Talk!  602-616-5160; jessica@movetheneedle.com</p>", 'ypo_link' => 'https://www.ypoconnect.org/#/memberProfile?memberId=81e7e23b-7630-e011-ae57-0050569257ef', 'eos_link' => NULL, 'facebook' => NULL, 'twitter' => NULL, 'linkedin' => NULL, 'user_id' => 9]
        ];
        DB::table('implementers')->insert($implementers);

        $testimonials = [
            ['id' => 1, 'slug' => 'testimonial-chris-lombardi', 'name' => 'Chris Lombardi', 'title' => NULL, 'testimonial' => 'Running a second generation family business has its challenges.  EOS provided me the framework to transition out of the “lifestyle family business” model and into collaborative business model with clearly defined goals, transparent communication, and documented processes to align everyone on the team.', 'implementer_id' => 1],
            ['id' => 2, 'slug' => 'testimonial-hawthorne-castro', 'name' => 'Jessica Hawthorne-Castro', 'title' => NULL, 'testimonial' => 'EOS has been a game changing operational platform. EOS brings various best-in-class operational elements together in one comprehensive system and makes everyone on your executive team and all employees accountable. Using an EOS implementer on a quarterly basis to keep the cadence up with your teams and the 90 day reset is key as well.', 'implementer_id' => 1],
            ['id' => 3, 'slug' => 'testimonial-todd-dipaola', 'name' => 'Todd Dipaola', 'title' => NULL, 'testimonial' => "Running on EOS transformed our ability to diagnose challenges and gave a simple powerful framework to quadrupling in 2 years. Its like a chiropractic adjustment-- you didn't know your spine was tweaked until you suddenly had the weight lifted off your shoulders.", 'implementer_id' => 1],
            ['id' => 4, 'slug' => 'testimonial-alex-amin', 'name' => 'Alex Amin', 'title' => NULL, 'testimonial' => 'We are in the third year of owning and operating a 200-person global software business.  The EOS framework has been essential in helping my partner and I run the day-to-day operations; keep all employees aligned on mission, vision and goals; and drive real growth.', 'implementer_id' => 1],
            ['id' => 5, 'slug' => 'testimonial-aaron-pick', 'name' => 'Aaron Pick', 'title' => NULL, 'testimonial' => 'EOS has been a game changer for us as a company.  More than anything, it keeps us aligned across the organization and helps our lead.', 'implementer_id' => 1],
            ['id' => 6, 'slug' => 'testimonial-christopher-j-floyd-ypo-new-england', 'name' => 'Christopher J. Floyd (YPO New England)', 'title' => 'President / CEO of C.E. Floyd Company', 'testimonial' => 'I took over the business from my father in 2015 and realized the business was underperforming its potential. I like to think big picture and focus on continuous improvement, while my employees have an engineering mindset that crave clarity and predictability. Three years after implementing EOS, my organizational structure, new leadership, clear accountabilities and long-term strategy are in place and clearly stated. We live our core values every day.', 'implementer_id' => 2],
            ['id' => 7, 'slug' => 'testimonial-daniel-koffler-ypo-metro-new-york', 'name' => 'Daniel Koffler (YPO Metro New York)', 'title' => 'Founder/President New Frontiers', 'testimonial' => 'The key difference between everything else I’ve ever been exposed to and EOS is the depth the system goes into in explaining HOW to run a business (from how to run a meeting, to how to hold people accountable, to how to differentiate between a goal and a strategy and a tactic and an action in the pursuit of achieving that goal—spoiler alert, it all starts with CORE VALUES (which made no sense to me prior and sounded pretty touchy-feely…until it clicked, and clarified in large part why previous attempts/approaches weren’t working.', 'implementer_id' => 2],
            ['id' => 8, 'slug' => 'testimonial-derek-mohamed-ypo-new-england', 'name' => 'Derek Mohamed (YPO New England)', 'title' => 'Managing Director Mohamed-Merola Wealth Management', 'testimonial' => 'I can’t say enough positive things about the EOS the impact that it has had on my business. For many years we tried to implement strategy around our culture, values, our long-term goals and our short-term goals, as well as finding the right people, managing people in the organization etc. When I first read Traction, it was an “ah-ha” moment. This was the first time I had ever seen all of these issues addressed in one place with a system that ties it all together. We started implementing the EOS system in our business in 2016. It’s no coincidence that our business has doubled in the four years since then, which is extremely unusual in our space with a business that has been running for over 20 years.   Anyone running a small or midsized businesses that wants to take it to the next level or just wants to see if there’s a way to run things more efficiently should explore EOS.', 'implementer_id' => 2],
            ['id' => 9, 'slug' => 'testimonial-patrick-condon', 'name' => 'Patrick Condon', 'title' => 'Founder, President FBC Remodel, Former YPO-Colorado', 'testimonial' => 'The EOS System transformed my business. For years I hit my head against the wall introducing complex business systems to my team without consistent success. This simple program helped me grow my leadership team and create consistent accountability and discipline. Our Implementer, Lisa, played THE critical role in our implementation of EOS. Overall, EOS allowed me to remove myself from the weeds and work on my business. Great operating system. Great ROI. Great results.', 'implementer_id' => 4],
            ['id' => 10, 'slug' => 'testimonial-jessica-billingsley', 'name' => 'Jessica Billingsley', 'title' => 'CEO, Akerna, YPO-Colorado member', 'testimonial' => 'Lisa understood the delicate dynamic of bringing together three companies and brought the perfect balance of listening, coaching, and teaching to help us achieve the desired result. At the end of the EOS session the entire leadership team rated the session an UNANIMOUS 10/10. We were able to leave united in our vision and our focus.', 'implementer_id' => 4],
            ['id' => 11, 'slug' => 'testimonial-amy-shepek', 'name' => 'Amy Shepek', 'title' => 'Alvarado Companies', 'testimonial' => 'The EOS Process around issue resolution has been one of the most valuable elements for us. We used to rehash the same “problems” week after week without taking action. Now the EOS structure guides us to get all the facts on the table, refrain from placing blame, identify the root cause and assign accountability to solve.', 'implementer_id' => 7],
            ['id' => 12, 'slug' => 'testimonial-nick-machol', 'name' => 'Nick Machol', 'title' => 'Machol & Johannes, LLC', 'testimonial' => 'EOS has fundamentally shifted the way we run our business. Everyone is on the same page and is extremely accountable. We’re now completing 4-5 needle-moving projects each quarter.', 'implementer_id' => 7],
            ['id' => 13, 'slug' => 'testimonial-don-hindman', 'name' => 'Don Hindman', 'title' => 'Johnson Storage & Moving Co', 'testimonial' => 'Since the beginning of our EOS implementation, we have noted a dramatic improvement in our company culture, values, and performance.  We are completing initiatives faster and more consistently and achieving improved net income even in the face of Covid. EOS have been a huge win for us.', 'implementer_id' => 7]
        ];
        DB::table('testimonials')->insert($testimonials);
    }
}
